version: "3.3"
services:
  mongodb:
    image: 'mongo'
    healthcheck: 
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: 'mongo-express'
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mern-front
    ports:
      - "8088:3000"
    volumes:
      - front-volume:/app
      - /app/node_modules

  backend:
    build: .
    container_name: mern-backend
    ports:
      - "5000:5000"
    volumes:
      - back-volume:/app
      - /app/node_modules

volumes:
  mongo-volume:
  front-volume:
  back-volume:
