pipeline {
    agent any
    stages {
        stage('Preparation') {
            steps {
                echo 'Preparation..'
            }
        }
        stage('Build and run app') {
            // steps {
            //     echo 'Build..'
            // }
            steps {
                echo "Branch: ${GIT_BRANCH}    Commit: ${GIT_COMMIT}"
                echo "Jenkins node: ${NODE_NAME}    Build tag: ${BUILD_TAG}"
                echo "Jenkins workspace: ${WORKSPACE}"
                sh 'ls -al'
                sh 'docker-compose up -d'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}